stages:
  - test
  - deploy
  
test:
  stage: test
  script:
  # TODO
  - echo "Running tests ..."
  
staging:
  stage: deploy
  script:
  - echo "Stopping OLD server"
  - apt-get update; apt-get install curl
  - curl localhost:5000/stopserver
  #- echo "Starting NEW server"
  #- cd servidor
  #- chmod 777 runserver.sh
  #- ./runserver.sh &
  
  only:
  - dev
 