image: docker:stable

stages:
  - test
  - deploy
  
test:
  stage: test
  script:
  # TODO
  - echo "Running tests ..."
  
staging:
  stage: deploy
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
  script:
  #- echo "Stopping OLD server"
  #- curl 150.162.6.91:5000/stopserver
  - echo "Starting NEW server"
  - cd servidor
  - chmod 777 runserver.sh
  - ./runserver.sh &
  
  only:
  - dev
 