stages:
  - test
  - deploy
  
test:
  stage: test
  script:
  # TODO
  - echo "Running tests ..."
  
staging:
  stage: deploy
  script:
  - echo "Starting server" 
  - cd servidor
  - sudo chmod 777 runserver.sh
  - sudo runserver.sh&
  
  only:
  - dev
 