stages:
  - test
  - deploy
  
test:
  stage: test
  script:
  # TODO
  - echo "Running tests ...."
  
staging:
  stage: deploy
  script:
  - echo "Starting server" 
  - cd servidor
  - sudo python3 application.py
  
  only:
  - dev
 